[project]
name = "ocr"
version = "0.1.0"
description = "OCR with Azure AI"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "httpx>=0.28.1",
    "ipykernel>=6.29.5",
    "pymupdf>=1.26.3",
    "python-dotenv>=1.1.0",
]
